# Generated by Django 5.0.6 on 2024-05-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(default='tr', max_length=10)),
                ('conversationId', models.CharField(blank=True, max_length=10)),
                ('token', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
        ),
    ]
