# Generated by Django 5.0.6 on 2024-06-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='status',
            field=models.CharField(choices=[('D', 'DELETE'), ('H', 'HIDE'), ('S', 'SHOW')], default='S', max_length=1),
        ),
    ]
