# Generated by Django 5.0.6 on 2024-06-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productimage_row'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='image',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='long_description',
            field=models.TextField(default=''),
        ),
    ]
