# Generated by Django 5.0.6 on 2024-06-12 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_productmodel_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='long_description',
        ),
    ]
