# Generated by Django 5.0.6 on 2024-06-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_commentmodel_productmodel_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='is_name_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
