# Generated by Django 5.0.6 on 2024-06-14 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_commentmodel_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='comments',
        ),
    ]
