# Generated by Django 5.0.6 on 2024-06-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_productmodel_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='status',
            field=models.CharField(choices=[('H', 'HIDE'), ('A', 'ADMIN_HIDE'), ('S', 'SHOW')], default='S', max_length=10),
        ),
    ]
